---
features:
  - |
    The following classses have been added.

    - ``designate::producer_task::delayed_notify``
    - ``designate::producer_task::periodic_exists``
    - ``designate::producer_task::periodic_secondary_refresh``
    - ``designate::producer_task::worker_periodic_recovery``
    - ``designate::producer_task::zone_purge``
